"""
research_summarizer.py
=================
Single-agent loop generated by the create-agent skill.

Conventions (see .claude/skills/create-agent/reference.md):
  - Model pinned to claude-haiku-4-5
  - Four-category error schema: transient | permission | validation | internal
  - Loop exits ONLY on stop_reason == "end_turn"
  - MAX_ITERATIONS is a safety valve, not a stop condition

Setup:
  pip install anthropic
  export ANTHROPIC_API_KEY="sk-ant-..."
  python research_summarizer.py
"""

import anthropic
import json

client = anthropic.Anthropic()
MODEL  = "claude-haiku-4-5"

# ─────────────────────────────────────────────
# MOCK CORPUS  (teaching data — swap for real docs/URLs later)
# ─────────────────────────────────────────────
FAKE_DOCS = {
    "doc-001": {
        "title": "Prompt caching overview",
        "topic": "prompt-caching",
        "body":  "Prompt caching lets you reuse large static prefixes across calls. "
                 "Cache hits cost ~10% of base input tokens. TTL is 5 minutes by default.",
    },
    "doc-002": {
        "title": "Tool use loop basics",
        "topic": "tool-use",
        "body":  "An agent loop alternates between model turns and tool execution. "
                 "Exit only on stop_reason == 'end_turn'; keep MAX_ITERATIONS as a safety valve.",
    },
    "doc-003": {
        "title": "Extended thinking",
        "topic": "thinking",
        "body":  "Extended thinking lets Claude reason in a hidden scratchpad before responding. "
                 "Useful for multi-step planning; budget tokens via the `thinking` parameter.",
    },
    "doc-004": {
        "title": "Batch API",
        "topic": "batch",
        "body":  "The Message Batches API processes async requests at 50% discount. "
                 "Best for non-latency-sensitive workloads up to 10k requests per batch.",
    },
    "doc-005": {
        "title": "Tool use loop pitfalls",
        "topic": "tool-use",
        "body":  "Common mistakes: appending tool_results before the assistant tool_use message, "
                 "treating MAX_ITERATIONS as a normal exit, swallowing tool errors silently.",
    },
}

# ─────────────────────────────────────────────
# TOOL SCHEMAS
# Each description covers WHAT, WHEN, WHAT NOT, WHAT RETURNED.
# ─────────────────────────────────────────────
tools = [
    {
        "name": "search_docs",
        "description": (
            "Search the documentation corpus by topic keyword and return matching doc IDs + titles. "
            "Call this FIRST to discover which documents exist on a topic before fetching them. "
            "Do NOT use this to read full document contents — use fetch_doc for that. "
            "Returns a JSON list of {doc_id, title, topic} matches (empty list if none)."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "topic": {
                    "type": "string",
                    "description": "Topic keyword to search, e.g. 'tool-use', 'caching', 'thinking'."
                }
            },
            "required": ["topic"]
        }
    },
    {
        "name": "fetch_doc",
        "description": (
            "Fetch the full body of a single document by its doc_id. "
            "Call this AFTER search_docs to read the actual content of a result. "
            "Do NOT call with a topic keyword — only valid doc_ids returned by search_docs work. "
            "Returns a JSON object with {doc_id, title, topic, body}."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "doc_id": {
                    "type": "string",
                    "description": "The exact doc_id (e.g. 'doc-001') returned by search_docs."
                }
            },
            "required": ["doc_id"]
        }
    },
]

# ─────────────────────────────────────────────
# TOOL IMPLEMENTATIONS  (mock data — replace with real integrations later)
# ─────────────────────────────────────────────
def execute_tool(tool_name: str, tool_input: dict) -> str:
    """Run a tool and return its result as a JSON string."""
    if tool_name == "search_docs":
        topic = tool_input.get("topic", "").strip().lower()
        if not topic:
            raise ValueError("topic must be a non-empty string")
        matches = [
            {"doc_id": doc_id, "title": d["title"], "topic": d["topic"]}
            for doc_id, d in FAKE_DOCS.items()
            if topic in d["topic"].lower() or topic in d["title"].lower()
        ]
        return json.dumps(matches)

    if tool_name == "fetch_doc":
        doc_id = tool_input.get("doc_id", "")
        if doc_id not in FAKE_DOCS:
            raise ValueError(f"unknown doc_id: {doc_id}")
        d = FAKE_DOCS[doc_id]
        return json.dumps({"doc_id": doc_id, **d})

    return json.dumps({"error": f"Unknown tool: {tool_name}"})


# ─────────────────────────────────────────────
# TOOL CALL HANDLER
# All errors become structured tool_result responses — never bare exceptions.
# ─────────────────────────────────────────────
def handle_tool_call(tool_name: str, tool_id: str, tool_input: dict) -> dict:
    print(f"  → Calling tool: {tool_name}({tool_input})")
    try:
        content = execute_tool(tool_name, tool_input)
        print(f"  ← Result: {content}")
        return {"type": "tool_result", "tool_use_id": tool_id, "content": content}

    except TimeoutError as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "transient", "isRetryable": True,
                    "description": f"Timeout calling {tool_name}: {e}",
                    "retryAfterMs": 2000})}

    except PermissionError as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "permission", "isRetryable": False,
                    "description": f"Access denied for {tool_name}: {e}"})}

    except ValueError as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "validation", "isRetryable": False,
                    "description": f"Invalid input for {tool_name}: {e}"})}

    except Exception as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "internal", "isRetryable": False,
                    "description": f"Unexpected error in {tool_name}: {e}"})}


# ─────────────────────────────────────────────
# AGENTIC LOOP
# Loop until stop_reason == "end_turn". MAX_ITERATIONS is the safety valve.
# ─────────────────────────────────────────────
def run_agent(user_message: str) -> str:
    messages = [{"role": "user", "content": user_message}]
    MAX_ITERATIONS = 50
    iteration = 0

    while iteration < MAX_ITERATIONS:
        iteration += 1

        response = client.messages.create(
            model=MODEL,
            max_tokens=4096,
            tools=tools,
            messages=messages,
        )

        if response.stop_reason == "end_turn":
            for block in response.content:
                if block.type == "text":
                    return block.text
            return ""

        if response.stop_reason == "tool_use":
            messages.append({"role": "assistant", "content": response.content})

            tool_results = []
            for block in response.content:
                if block.type == "tool_use":
                    tool_results.append(handle_tool_call(block.name, block.id, block.input))

            messages.append({"role": "user", "content": tool_results})

    return "Error: agent did not complete within the iteration limit"


if __name__ == "__main__":
    print("Running agent...")
    answer = run_agent(
        "Research what the docs say about the tool-use loop and give me a short summary "
        "of the key rules and common pitfalls."
    )
    print(f"\nFinal answer: {answer}")
