"""
{{AGENT_NAME}}.py
=================
Multi-agent (coordinator + subagents) system generated by the create-agent skill.

Patterns (see .claude/skills/create-agent/reference.md):
  - Coordinator decomposes the task and delegates to focused subagents
  - Subagents get ONLY the tools + context the coordinator hands them
  - Findings flow as STRUCTURED DICTS, not free-form prose
  - PreToolUse hooks: policy gates (can block)
  - PostToolUse hooks: reshape raw → model-friendly (can rewrite)
  - Same four-category error schema and end_turn exit as single-agent

Setup:
  pip install anthropic
  export ANTHROPIC_API_KEY="sk-ant-..."
  python {{AGENT_NAME}}.py
"""

import anthropic
import json

client = anthropic.Anthropic()
MODEL  = "claude-haiku-4-5"

# ─────────────────────────────────────────────
# MOCK DATA  (no real APIs — replace with real integrations later)
# ─────────────────────────────────────────────
FAKE_DB = {
    # TODO: populate with mock records
}

# Mutable session state shared across subagents within one coordinator run.
session = {
    # TODO: track flags the hooks read/write (e.g. customer_verified)
}

# ─────────────────────────────────────────────
# TOOL FUNCTIONS  (raw — PostToolUse hooks can normalize their output)
# ─────────────────────────────────────────────
def {{TOOL_FN_NAME}}(**kwargs) -> dict:
    # TODO: implement
    return {"found": False, "error": "not implemented"}

TOOL_REGISTRY = {
    "{{TOOL_NAME}}": {{TOOL_FN_NAME}},
}

# ─────────────────────────────────────────────
# PRE-TOOL-USE HOOKS  (policy gates — can BLOCK)
# Each hook returns {"allowed": True} or {"allowed": False, "reason": "..."}.
# First hook that returns allowed=False wins.
# ─────────────────────────────────────────────
def example_policy_gate(tool_name, tool_params):
    # TODO: replace with real gate (spend cap, auth check, destructive review…)
    return {"allowed": True}

PRE_TOOL_HOOKS = [example_policy_gate]

def apply_pre_tool_hooks(tool_name, tool_params):
    for hook in PRE_TOOL_HOOKS:
        decision = hook(tool_name, tool_params)
        if not decision.get("allowed", True):
            return decision
    return {"allowed": True}

# ─────────────────────────────────────────────
# POST-TOOL-USE HOOKS  (reshape raw data BEFORE the model sees it)
# Each hook receives the previous hook's output. Run in order.
# ─────────────────────────────────────────────
def example_normalizer(tool_name, raw_result):
    # TODO: e.g. status codes → words, Unix ts → dates, cents → dollars
    return raw_result

POST_TOOL_HOOKS = [example_normalizer]

def apply_post_tool_hooks(tool_name, raw_result):
    result = raw_result
    for hook in POST_TOOL_HOOKS:
        result = hook(tool_name, result)
    return result

# ─────────────────────────────────────────────
# TOOL SCHEMAS
# Each description should answer: WHAT, WHEN, WHAT NOT, WHAT RETURNED.
# ─────────────────────────────────────────────
TOOLS = [
    {
        "name": "{{TOOL_NAME}}",
        "description": (
            "{{TOOL_WHAT}} "
            "Call this when {{TOOL_WHEN}}. "
            "Do NOT use this for {{TOOL_NOT}}. "
            "Returns {{TOOL_RETURNS}}."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "{{PARAM_NAME}}": {
                    "type": "string",
                    "description": "{{PARAM_DESCRIPTION}}"
                }
            },
            "required": ["{{PARAM_NAME}}"]
        }
    },
]

# ─────────────────────────────────────────────
# TOOL CALL HANDLER  (pre-hook → tool → post-hook → structured errors)
# ─────────────────────────────────────────────
def handle_tool_call(tool_name: str, tool_id: str, tool_input: dict) -> dict:
    decision = apply_pre_tool_hooks(tool_name, tool_input)
    if not decision["allowed"]:
        print(f"  [HOOK] BLOCKED {tool_name}({tool_input}) — {decision.get('reason')}")
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps(decision)}

    print(f"  [TOOL] Calling {tool_name}({tool_input})")
    try:
        raw_result = TOOL_REGISTRY[tool_name](**tool_input)
        result = apply_post_tool_hooks(tool_name, raw_result)
        return {"type": "tool_result", "tool_use_id": tool_id,
                "content": json.dumps(result)}

    except TimeoutError as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "transient", "isRetryable": True,
                    "description": f"Timeout calling {tool_name}: {e}",
                    "retryAfterMs": 2000})}

    except PermissionError as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "permission", "isRetryable": False,
                    "description": f"Access denied for {tool_name}: {e}"})}

    except ValueError as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "validation", "isRetryable": False,
                    "description": f"Invalid input for {tool_name}: {e}"})}

    except Exception as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "internal", "isRetryable": False,
                    "description": f"Unexpected error in {tool_name}: {e}"})}


# ─────────────────────────────────────────────
# AGENTIC LOOP  (shared by every subagent)
# ─────────────────────────────────────────────
def run_agentic_loop(system_prompt: str, user_message: str, tools: list) -> str:
    messages = [{"role": "user", "content": user_message}]
    MAX_ITERATIONS = 50
    iteration = 0

    while iteration < MAX_ITERATIONS:
        iteration += 1
        response = client.messages.create(
            model=MODEL, max_tokens=1024,
            system=system_prompt, tools=tools, messages=messages,
        )

        if response.stop_reason == "end_turn":
            return next((b.text for b in response.content if hasattr(b, "text")), "")

        if response.stop_reason == "tool_use":
            messages.append({"role": "assistant", "content": response.content})
            tool_results = [
                handle_tool_call(b.name, b.id, b.input)
                for b in response.content if b.type == "tool_use"
            ]
            messages.append({"role": "user", "content": tool_results})

    return "Error: agent did not complete within the iteration limit"


# ─────────────────────────────────────────────
# SUBAGENT INVOCATION  (returns a STRUCTURED finding, not prose)
# ─────────────────────────────────────────────
def run_subagent(role: str, task_prompt: str, tools: list) -> dict:
    print(f"\n  ── Subagent [{role}] starting ──")
    system_prompt = (
        f"You are the {role} subagent. Be concise. "
        "Return factual results only. Do not make up data."
    )
    result_text = run_agentic_loop(system_prompt, task_prompt, tools)
    return {
        "subagent_role": role,
        "task":          task_prompt[:100],
        "result":        result_text,
        "status":        "complete",
    }


# ─────────────────────────────────────────────
# COORDINATOR  (decompose → delegate → aggregate)
# Each subagent gets ONLY the tools and context the coordinator hands it.
# Findings flow as structured dicts, not free-form prose.
# ─────────────────────────────────────────────
def coordinator({{COORDINATOR_PARAMS}}) -> str:
    print("\n" + "="*60)
    print("COORDINATOR: Decomposing task")
    print("="*60)

    # Reset session state at the start of every coordinator run
    # TODO: reset any flags the hooks rely on
    # session["customer_verified"] = False

    # ── Subtask 1 ──────────────────────────────────────────
    subtask_1_finding = run_subagent(
        role="{{SUBAGENT_1_ROLE}}",
        task_prompt="{{SUBAGENT_1_TASK}}",
        tools=[TOOLS[0]],   # narrowed: only the tools this subagent needs
    )
    print(f"\n  [COORDINATOR] Finding 1:\n  {json.dumps(subtask_1_finding, indent=2)}")

    # ── Subtask 2 ──────────────────────────────────────────
    # Pass the prior finding as a STRUCTURED object, not prose.
    subtask_2_prompt = (
        f"{{SUBAGENT_2_TASK}}\n\n"
        f"PRIOR FINDING:\n{json.dumps(subtask_1_finding, indent=2)}"
    )
    subtask_2_finding = run_subagent(
        role="{{SUBAGENT_2_ROLE}}",
        task_prompt=subtask_2_prompt,
        tools=TOOLS,        # narrow further if this subagent only needs a subset
    )

    # ── Aggregate ──────────────────────────────────────────
    print("\n" + "="*60)
    print("COORDINATOR: Aggregating results")
    print("="*60)
    summary = (
        f"\nResult 1: {subtask_1_finding['result']}"
        f"\nResult 2: {subtask_2_finding['result']}\n"
    )
    print(summary)
    return summary


if __name__ == "__main__":
    coordinator({{EXAMPLE_COORDINATOR_ARGS}})
