"""
{{AGENT_NAME}}.py
=================
Single-agent loop generated by the create-agent skill.

Conventions (see .claude/skills/create-agent/reference.md):
  - Model pinned to claude-haiku-4-5
  - Four-category error schema: transient | permission | validation | internal
  - Loop exits ONLY on stop_reason == "end_turn"
  - MAX_ITERATIONS is a safety valve, not a stop condition

Setup:
  pip install anthropic
  export ANTHROPIC_API_KEY="sk-ant-..."
  python {{AGENT_NAME}}.py
"""

import anthropic
import json

client = anthropic.Anthropic()
MODEL  = "claude-haiku-4-5"

# ─────────────────────────────────────────────
# TOOL SCHEMAS
# Each description should answer: WHAT, WHEN, WHAT NOT, WHAT RETURNED.
# ─────────────────────────────────────────────
tools = [
    {
        "name": "{{TOOL_NAME}}",
        "description": (
            "{{TOOL_WHAT}} "
            "Call this when {{TOOL_WHEN}}. "
            "Do NOT use this for {{TOOL_NOT}}. "
            "Returns {{TOOL_RETURNS}}."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "{{PARAM_NAME}}": {
                    "type": "string",
                    "description": "{{PARAM_DESCRIPTION}}"
                }
            },
            "required": ["{{PARAM_NAME}}"]
        }
    }
]

# ─────────────────────────────────────────────
# TOOL IMPLEMENTATIONS  (mock data — replace with real integrations later)
# ─────────────────────────────────────────────
def execute_tool(tool_name: str, tool_input: dict) -> str:
    """Run a tool and return its result as a JSON string."""
    if tool_name == "{{TOOL_NAME}}":
        # TODO: replace with real logic
        mock_data = {"{{MOCK_KEY}}": "{{MOCK_VALUE}}"}
        key = tool_input.get("{{PARAM_NAME}}", "")
        if key in mock_data:
            return json.dumps(mock_data[key])
        return json.dumps({"error": f"No record for {key}"})

    return json.dumps({"error": f"Unknown tool: {tool_name}"})


# ─────────────────────────────────────────────
# TOOL CALL HANDLER
# All errors become structured tool_result responses — never bare exceptions.
# ─────────────────────────────────────────────
def handle_tool_call(tool_name: str, tool_id: str, tool_input: dict) -> dict:
    print(f"  → Calling tool: {tool_name}({tool_input})")
    try:
        content = execute_tool(tool_name, tool_input)
        print(f"  ← Result: {content}")
        return {"type": "tool_result", "tool_use_id": tool_id, "content": content}

    except TimeoutError as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "transient", "isRetryable": True,
                    "description": f"Timeout calling {tool_name}: {e}",
                    "retryAfterMs": 2000})}

    except PermissionError as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "permission", "isRetryable": False,
                    "description": f"Access denied for {tool_name}: {e}"})}

    except ValueError as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "validation", "isRetryable": False,
                    "description": f"Invalid input for {tool_name}: {e}"})}

    except Exception as e:
        return {"type": "tool_result", "tool_use_id": tool_id, "is_error": True,
                "content": json.dumps({
                    "errorCategory": "internal", "isRetryable": False,
                    "description": f"Unexpected error in {tool_name}: {e}"})}


# ─────────────────────────────────────────────
# AGENTIC LOOP
# Loop until stop_reason == "end_turn". MAX_ITERATIONS is the safety valve.
# ─────────────────────────────────────────────
def run_agent(user_message: str) -> str:
    messages = [{"role": "user", "content": user_message}]
    MAX_ITERATIONS = 50
    iteration = 0

    while iteration < MAX_ITERATIONS:
        iteration += 1

        response = client.messages.create(
            model=MODEL,
            max_tokens=4096,
            tools=tools,
            messages=messages,
        )

        if response.stop_reason == "end_turn":
            for block in response.content:
                if block.type == "text":
                    return block.text
            return ""

        if response.stop_reason == "tool_use":
            # 1) append assistant message FIRST
            messages.append({"role": "assistant", "content": response.content})

            # 2) run all tools
            tool_results = []
            for block in response.content:
                if block.type == "tool_use":
                    tool_results.append(handle_tool_call(block.name, block.id, block.input))

            # 3) append tool_results as a single user message
            messages.append({"role": "user", "content": tool_results})

    return "Error: agent did not complete within the iteration limit"


if __name__ == "__main__":
    print("Running agent...")
    answer = run_agent("{{EXAMPLE_USER_MESSAGE}}")
    print(f"\nFinal answer: {answer}")
